name: tiktok_transitions_jm
version: 0.0.8
description: A Flutter plugin for iOS and Android to create a tiktok-like interface using the "video_player" package
homepage: https://github.com/JeisonManuelVargas/tiktok_transitions_jm

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
